### ISSUE TITLE
Instana agent looking for v1beta1/cronjobs on kubernetes v1.26.4

### ISSUE THREAD

**Issue by andrew-jones** [instana/instana-agent-docker#156]
I can no longer open support cases with Instana/IBM as the Search account dropdown doesn't work.  Can't talk to an agent as "You currently do not have permission to start a chat with the live agent. If you would like to request access, please visit the page [linked here](https://www.ibm.com/mysupport/s/supportaccess), and click on the "Request Access" button."  And can't request access to talk to an agent via the link.  So not sure how to get help but here is my issue. 

---

We are seeing errors from the Instana agent looking for cronjobs.   We have just migrated to AWS EKS at kubernetes v1.26.4.  Cronjobs have left beta in 1.26 but the agent appears to be looking in the v1beta1 path.

$ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.4-eks-0a21954

Logs:

2023-05-18T05:31:34.409+00:00 | INFO  | instana-scheduler-thread-2-1     | ableResourceInfo | com.instana.sensor-kubernetes - 1.2.140 | Start watching all cronjobs...
2023-05-18T05:31:34.416+00:00 | ERROR | instana-scheduler-thread-2-1     | ableResourceInfo | com.instana.sensor-kubernetes - 1.2.140 | Could not perform watch on all cronjobs
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.100.0.1/apis/batch/v1beta1/cronjobs?limit=500. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:635) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[?:?]
	at com.instana.agent.kubernetes.sensor.client.WatchableResourceInfo.list(WatchableResourceInfo.java:119) ~[?:?]
	at com.instana.agent.kubernetes.sensor.client.WatchableResourceInfo.start(WatchableResourceInfo.java:85) ~[?:?]
	at com.instana.agent.kubernetes.sensor.client.WatchGroupLifeCycle.start(WatchGroupLifeCycle.java:59) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_362]
	at com.instana.agent.kubernetes.sensor.client.WatchGroupLifeCycle.start(WatchGroupLifeCycle.java:46) ~[?:?]
	at com.instana.agent.kubernetes.sensor.LeaderWatchGroup.watchResources(LeaderWatchGroup.java:230) ~[?:?]
	at com.instana.agent.kubernetes.sensor.LeaderWatchGroup.start(LeaderWatchGroup.java:192) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4705) ~[?:1.8.0_362]
	at com.instana.agent.kubernetes.sensor.state.WatchGroupManager.updatePodWatchBehaviour(WatchGroupManager.java:38) ~[?:?]
	at com.instana.agent.kubernetes.sensor.Kubernetes.lambda$activate$2(Kubernetes.java:221) ~[?:?]
	at com.instana.agent.api.ObservableRunnable.run(ObservableRunnable.java:65) ~[?:?]
	at com.instana.agent.main.impl.scheduler.SchedulerImpl.lambda$wrappedObserverableRunnable$0(SchedulerImpl.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [!/:4.1.91.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]

**Comment by Niyaskva** [comment]
Hi Team
We have also faced similar issue. Tried by installing various version of instana agent(1.2.60). Cluster is running with AKS 1.25.6. So during upgrade cronjob apiversion has changed from v1beta1 to v1. But still instana agent try to monitor v1beta1 instead of v1. Could someone please share if there is any fix?

2023-06-17T06:14:38.725+00:00 | ERROR | instana-scheduler-thread-3-2     | ableResourceInfo | com.instana.sensor-kubernetes - 1.2.140 | Could not perform watch on all cronjobs
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.0.0.1/apis/batch/v1beta1/cronjobs?limit=500. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
